### ISSUE TITLE
InvalidURIError

### ISSUE THREAD

**Issue by iamademar** [kennym/ideone-ruby-api#2]
I tried:

``` ruby
require 'ideone'

@i = Ideone.new('fakeusername', 'fakepassword')
 Rails.logger.info '------------ inspect results ------------------'
 Rails.logger.info @i.test
 Rails.logger.info '--------------------------------------------------'
```

I got an error message:
URI::InvalidURIError (bad URI(is not URI?): {:host=>"ideone.com", :path=>"/api/1/service.wsdl", :port=>"80", :query=>nil, :scheme=>"http", :headers=>{}, :body=>nil, :ssl_verify_peer=>true})

**Comment by kennym** [comment]
Which version of `ideone-ruby-api` are you using? ( `gem list --local | grep ideone` )

**Comment by iamademar** [comment]
verion 2.0.0

**Comment by kennym** [comment]
@iamademar please download 2.1.0 and try there. Using wrong credentials should now raise a friendly error message.

Please, re-open if you're seeing unexpected behavior. Thanks for reporting the issue!
