### ISSUE TITLE
Meaning of :result=>15?

### ISSUE THREAD

**Issue by tejasmanohar** [kennym/ideone-ruby-api#3]
How do I find the output of my code submission?  What does '15' mean?

`i.submission_status("TOKEN")

{:status=>0, :result=>15}`

**Comment by kennym** [comment]
Look up the documentation (page 10): http://ideone.com/files/ideone-api.pdf

![screen shot 2015-01-13 at 1 36 50 pm](https://cloud.githubusercontent.com/assets/160117/5724263/3ce182d2-9b29-11e4-86e6-ec0905b85c47.png)

**Comment by tejasmanohar** [comment]
how to get the actual result? like STDOUT result of my code?

**Comment by kennym** [comment]
`i.submission_status("TOKEN")[:result]`
